[package]
name = "mandelbrot_set_gl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18"
glium = "0.32"
image = "0.24.7"
ffmpeg-next = "6.0.0"
